CREATE TABLE IF NOT EXISTS block_dispatcher (
    exp_id VARCHAR,
    simulation_step INTEGER,
    timestamp TIMESTAMP,
    agent_id INTEGER,
    target_block VARCHAR,
    reason VARCHAR,
    possible_blocks VARCHAR,
    ctx_time VARCHAR,
    ctx_need VARCHAR,
    ctx_intention VARCHAR,
    ctx_emotion VARCHAR,
    ctx_thought VARCHAR,
    ctx_location VARCHAR,
    ctx_area_info VARCHAR,
    ctx_weather VARCHAR,
    ctx_temperature INTEGER,
    ctx_other_info VARCHAR,
    ctx_plan_target VARCHAR
);
