CREATE TABLE IF NOT EXISTS static_agent_attributes (
	exp_id LowCardinality(String),
	simulation_step Int32,
	timestamp DateTime64(3),
	agent_id Int32,
	type LowCardinality(String),
	home_aoi_id Int32,
	work_aoi_id Int32,
	name String CODEC(ZSTD(3)),
	gender LowCardinality(String),
	age Int32,
	education LowCardinality(String),
	household LowCardinality(String),
	life_stage LowCardinality(String),
	skill String CODEC(ZSTD(3)),
	occupation LowCardinality(String),
	work_skill Float32,
	firm_id Int32,
	government_id Int32,
	bank_id Int32,
	nbs_id Int32,
	preferences_chronotype LowCardinality(String),
	preferences_risk_tolerance Float32,
	preferences_spending_tendency Float32,
	preferences_social_frequency Float32,
	preferences_work_ethic Float32,
	preferences_leisure_preference LowCardinality(String),
	hobbies Array(String),
	personality String CODEC(ZSTD(3)),
	big5_openness Int32,
	big5_conscientiousness Int32,
	big5_extraversion Int32,
	big5_agreeableness Int32,
	big5_neuroticism Int32,
	income Float32,
	currency Float32,
	residence String CODEC(ZSTD(3)),
	city String CODEC(ZSTD(3)),
	race String CODEC(ZSTD(3)),
	religion String CODEC(ZSTD(3)),
	marriage_status LowCardinality(String),
	background_story String CODEC(ZSTD(3))
)
ENGINE = MergeTree()
ORDER BY (exp_id, agent_id, timestamp)
PARTITION BY exp_id
